import fs from "node:fs/promises";
import path from "node:path";
import {
  parseCsvLine,
  csvEscape,
  safeReadText,
  safeReadDirEntries,
  safeStat,
  asRelativeFromRoot,
  safeExecGit
} from "./utils.mjs";

export async function collectUrls(rootDir, options) {
  const urls = [...options.urls];
  if (options.file) {
    const fileContent = await fs.readFile(path.resolve(rootDir, options.file), "utf8");
    for (const line of fileContent.split(/\r?\n/)) {
      const trimmed = line.trim();
      if (!trimmed || trimmed.startsWith("#")) {
        continue;
      }
      urls.push(trimmed);
    }
  }
  return [...new Set(urls)];
}

export function normalizeGithubUrl(rawUrl) {
  let url;
  try {
    url = new URL(rawUrl);
  } catch {
    throw new Error(`Invalid URL: ${rawUrl}`);
  }

  if (url.hostname !== "github.com") {
    throw new Error(`Only github.com repository URLs are supported right now: ${rawUrl}`);
  }

  const parts = url.pathname.split("/").filter(Boolean);
  if (parts.length < 2) {
    throw new Error(`GitHub URL must point to a repository: ${rawUrl}`);
  }

  const owner = parts[0];
  const name = parts[1].replace(/\.git$/i, "");
  const normalizedRepoUrl = `https://github.com/${owner}/${name}`;

  return {
    rawUrl,
    normalizedRepoUrl,
    owner,
    name,
    slug: `${owner}__${name}`.toLowerCase(),
    host: "github.com"
  };
}

export function createRunId(now = new Date()) {
  return now.toISOString().replace(/[:.]/g, "-");
}

async function readQueue(queuePath) {
  const raw = await fs.readFile(queuePath, "utf8");
  const lines = raw.split(/\r?\n/).filter(Boolean);
  const header = lines[0].split(";");
  const rows = lines.slice(1).map((line) => {
    const values = parseCsvLine(line);
    return Object.fromEntries(header.map((key, index) => [key, values[index] ?? ""]));
  });
  return { header, rows };
}

async function writeQueue(queuePath, header, rows) {
  const lines = [header.join(";")];
  for (const row of rows) {
    lines.push(header.map((key) => csvEscape(row[key] ?? "")).join(";"));
  }
  await fs.writeFile(queuePath, `${lines.join("\n")}\n`, "utf8");
}

export async function upsertQueueEntry(rootDir, config, entry) {
  const queuePath = path.join(rootDir, config.queueFile);
  const { header, rows } = await readQueue(queuePath);
  for (const key of Object.keys(entry)) {
    if (!header.includes(key)) {
      header.push(key);
    }
  }
  const index = rows.findIndex(
    (row) =>
      row.project_key === entry.project_key &&
      row.normalized_repo_url === entry.normalized_repo_url
  );

  if (index >= 0) {
    const previous = rows[index];
    rows[index] = {
      ...previous,
      ...entry,
      created_at: previous.created_at || entry.created_at
    };
  } else {
    rows.push(entry);
  }

  await writeQueue(queuePath, header, rows);
}

export async function loadQueueEntries(rootDir, config) {
  const queuePath = path.join(rootDir, config.queueFile);
  const { rows } = await readQueue(queuePath);
  return rows;
}

export async function loadLandkarteEntries(rootDir) {
  try {
    const { rows } = await readQueue(path.join(rootDir, "repo_landkarte.csv"));
    return rows;
  } catch {
    return [];
  }
}

async function countWatchlistEntries(rootDir, project) {
  if (!project.watchlistFile) {
    return 0;
  }
  const content = await safeReadText(path.join(rootDir, project.watchlistFile));
  if (!content) {
    return 0;
  }
  return content
    .split(/\r?\n/)
    .map((line) => line.trim())
    .filter((line) => line && !line.startsWith("#"))
    .length;
}

async function findLatestRun(rootDir, config) {
  const runsRoot = path.join(rootDir, config.runtimeRoot ?? "runs");
  const projectDirs = await safeReadDirEntries(runsRoot);
  const candidates = [];

  for (const projectDir of projectDirs) {
    if (!projectDir.isDirectory()) {
      continue;
    }
    const projectPath = path.join(runsRoot, projectDir.name);
    const runDirs = await safeReadDirEntries(projectPath);
    for (const runDir of runDirs) {
      if (!runDir.isDirectory()) {
        continue;
      }
      const runPath = path.join(projectPath, runDir.name);
      const stat = await safeStat(runPath);
      if (!stat) {
        continue;
      }
      candidates.push({
        projectKey: projectDir.name,
        runId: runDir.name,
        relativePath: asRelativeFromRoot(rootDir, runPath),
        modifiedAt: stat.mtime.toISOString()
      });
    }
  }

  candidates.sort((left, right) => right.modifiedAt.localeCompare(left.modifiedAt));
  return candidates[0] ?? null;
}

function buildPatternpilotStatusMarkdown({ generatedAt, gitInfo, config, queueEntries, landkarteEntries, projectSnapshots, latestRun, lastContext }) {
  const featureLine = [
    "intake",
    "promotion",
    "discovery",
    "watchlist_review",
    "html_reports",
    "workspace_mode"
  ].join(", ");

  return `# Patternpilot Status

<!-- Auto-generated by patternpilot CLI context refresh. Do not edit manually. -->

- last_updated: ${generatedAt}
- branch: ${gitInfo.branch || "-"} | head: ${gitInfo.head || "-"}
- default_project: ${config.defaultProject ?? "-"} | configured_projects: ${projectSnapshots.length}
- queue_entries: ${queueEntries.length} | curated_repos: ${landkarteEntries.length}
- capabilities: ${featureLine}
- discovery_profiles: focused, balanced, expansive, max
- analysis_profiles: balanced, architecture, sources, distribution, risk
- analysis_depths: quick, standard, deep
- report_views: compact, standard, full
- latest_run: ${latestRun ? `${latestRun.projectKey}/${latestRun.runId}` : "none"}
- latest_run_path: ${latestRun?.relativePath ?? "-"}
- last_command: ${lastContext.command ?? "-"} | last_project: ${lastContext.projectKey ?? "-"} | last_mode: ${lastContext.mode ?? "-"}
- last_report: ${lastContext.reportPath ?? "-"}

## Current Interpretation

- target_repo_context_model: run_scoped_context_sources
- hardwired_project_surface: none
- context_rule: Patternpilot reads configured repo context for each target project and exposes what it read in dossiers and HTML reports.
- handoff_next_step: chain_run_automation_with_quality_gates

## Project Surfaces

${projectSnapshots.map((project) => `- ${project.projectKey}: context_files=${project.contextFileCount} | context_dirs=${project.contextDirectoryCount} | watchlist=${project.watchlistCount} | intake_root=${project.intakeRoot} | promotion_root=${project.promotionRoot} | review_root=${project.reviewRoot} | report_root=${project.reportRoot}`).join("\n")}

## Quick Links

- agent_context: AGENT_CONTEXT.md
- claude_context: CLAUDE.md
- mission_vision: docs/foundation/MISSION_VISION.md
- operating_model: docs/foundation/OPERATING_MODEL.md
- report_output_model: docs/reference/REPORT_OUTPUT_MODEL.md
- report_ui_framework: docs/reference/REPORT_UI_FRAMEWORK.md
- automation_roadmap: docs/foundation/AUTOMATION_ROADMAP.md
- open_questions: OPEN_QUESTION.md
- config: patternpilot.config.json
- queue: repo_intake_queue.csv
- landkarte: repo_landkarte.csv
`;
}

function buildPatternpilotOpenQuestionMarkdown({ generatedAt, latestRun }) {
  return `# Open Questions

*Arbeitsdokument fuer offene Architektur-, Produkt- und Betriebsfragen in \`patternpilot\`.*

## Zweck

Diese Datei haelt nur Fragen fest, die fuer die weitere Produktreife von Patternpilot wirklich relevant sind.

Sie ist bewusst kein Sammelbecken fuer beliebige Ideen.

## Aktualisierung

Diese Datei wird zusammen mit \`STATUS.md\` als operative Uebergabeflaeche mitgefuehrt.

- last_updated: ${generatedAt}
- latest_run_reference: ${latestRun ? `${latestRun.projectKey}/${latestRun.runId}` : "none"}

## Handoff Note

- settled_now: target-repo context is run-scoped and transparent, not a hardwired product identity.
- next_recommended_step: build the automatic chain run with blacklist, allowlist, limits, and quality gates.

## Aktuell offene Fragen

### OQ-001 — REPORT_UI_DIRECTION

- prioritaet: BALD
- frage: Welche finale visuelle Richtung soll die HTML-Report-Schicht bekommen, bevor daraus eine spaetere App- oder Web-Oberflaeche wird?
- warum_offen: Die technische HTML-Schicht steht, aber Designsystem, visuelle Sprache und moegliche Branding-Regeln sind noch nicht final entschieden.
- naechster_sinnvoller_schritt: Ein verbindliches Report-UI-Framework mit Farben, Typografie, Komponenten und Chart-Patterns festziehen.

### OQ-002 — CHAIN_RUN_AUTOMATION

- prioritaet: JETZT
- frage: Wie soll der vollautomatische Kettenlauf \`discover -> watchlist -> intake -> review\` standardmaessig orchestriert werden?
- warum_offen: Die einzelnen Bausteine existieren, aber der integrierte End-to-End-Run mit sauberen Guards, Limits und Quality-Gates ist noch nicht gebaut.
- naechster_sinnvoller_schritt: Einen eigenen Chain-Run-Command mit Blacklist/Allowlist und Safety-Limits einfuehren.

### OQ-003 — QUALITY_FILTERS_FOR_DISCOVERY

- prioritaet: JETZT
- frage: Welche Blacklist-, Allowlist- und Qualitaetsregeln sollen Discovery-Kandidaten vor dem Watchlist-Handoff filtern?
- warum_offen: Discovery ist heuristisch stabil, aber fuer echte Produktnutzung fehlen noch harte Ausschluss- und Vertrauensregeln.
- naechster_sinnvoller_schritt: Policy-Dateien fuer ausgeschlossene Plattformen, Mindestsignale und bevorzugte Musterfamilien einfuehren.

### OQ-004 — GITHUB_APP_CUTOVER

- prioritaet: BALD
- frage: Wann soll Patternpilot vom PAT-Zwischenzustand auf echten GitHub-App-Betrieb umgestellt werden?
- warum_offen: Die Scaffolds sind da, aber App-Deployment, Webhooks und Installationsmodell sind noch nicht produktiv angeschlossen.
- naechster_sinnvoller_schritt: GitHub-App registrieren, Secrets setzen und einen ersten Live-Flow gegen reale Repos pruefen.

### OQ-005 — LLM_AUGMENTATION_BOUNDARY

- prioritaet: SPAETER
- frage: Wo ergaenzt spaeter eine LLM-Schicht die heuristische Engine sinnvoll, ohne den belastbaren Kern zu verwischen?
- warum_offen: Der aktuelle Fokus liegt bewusst auf einer halluzinationsarmen, reproduzierbaren Basis.
- naechster_sinnvoller_schritt: Erst nach stabiler Discovery-, Review- und Report-Schicht LLM-Einsatz nur fuer Verdichtung und Briefing pruefen.
`;
}

export async function refreshOperationalDocs(rootDir, config, context = {}) {
  const queueEntries = await loadQueueEntries(rootDir, config);
  const landkarteEntries = await loadLandkarteEntries(rootDir);
  const latestRun = await findLatestRun(rootDir, config);
  const projectSnapshots = [];

  for (const [projectKey, project] of Object.entries(config.projects ?? {})) {
    const bindingPath = project.projectBindingFile ? path.join(rootDir, project.projectBindingFile) : null;
    let contextFileCount = 0;
    let contextDirectoryCount = 0;
    if (bindingPath) {
      const bindingContent = await safeReadText(bindingPath);
      if (bindingContent) {
        try {
          const binding = JSON.parse(bindingContent);
          contextFileCount = binding.readBeforeAnalysis?.length ?? 0;
          contextDirectoryCount = binding.referenceDirectories?.length ?? 0;
        } catch {
          contextFileCount = 0;
          contextDirectoryCount = 0;
        }
      }
    }
    projectSnapshots.push({
      projectKey,
      contextFileCount,
      contextDirectoryCount,
      watchlistCount: await countWatchlistEntries(rootDir, project),
      intakeRoot: project.intakeRoot ?? "-",
      promotionRoot: project.promotionRoot ?? "-",
      reviewRoot: `projects/${projectKey}/reviews`,
      reportRoot: `projects/${projectKey}/reports`
    });
  }

  const generatedAt = new Date().toISOString();
  const gitInfo = {
    branch: safeExecGit(rootDir, ["branch", "--show-current"]),
    head: safeExecGit(rootDir, ["rev-parse", "--short", "HEAD"])
  };
  const statusContent = buildPatternpilotStatusMarkdown({
    generatedAt,
    gitInfo,
    config,
    queueEntries,
    landkarteEntries,
    projectSnapshots,
    latestRun,
    lastContext: context
  });
  const openQuestionsContent = buildPatternpilotOpenQuestionMarkdown({
    generatedAt,
    latestRun
  });

  await fs.writeFile(path.join(rootDir, "STATUS.md"), `${statusContent}\n`, "utf8");
  await fs.writeFile(path.join(rootDir, "OPEN_QUESTION.md"), `${openQuestionsContent}\n`, "utf8");
}

// Re-export readQueue and writeQueue for promotion module
export { readQueue, writeQueue };
